import { makeStyles } from "@material-ui/core/styles";
import bgImg from "../Images/bg-img.png";

const useStyles = makeStyles((theme) => ({
	root: {
		minHeight: "100vh",
		"& .MuiInput-underline:before": {
			borderBottom: "1.2px solid rgba(0, 0, 0, 0.2)",
		},
	},
	welcome: {
		fontSize: 26,
		paddingBottom: 20,
		color: "#000000",
		fontWeight: 700,
		fontFamily: "'Open Sans'",
	},
	heroText: {
		fontSize: 26,
		fontFamily: "'Open Sans'",
		textAlign: "center",
		color: "white",
		marginTop: 30,
		maxWidth: 300,
	},
	overlay: {
		backgroundImage:
			"linear-gradient(180deg, rgb(58,141,255, 0.75) 0%, rgb(134,185,255, 0.75) 100%)",
		backgroundSize: "cover",
		backgroundPosition: "center",
		flexDirection: "column",
		minHeight: "100vh",
		paddingBottom: 145,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	authWrapper: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		flexDirection: "column",
		minHeight: "100vh",
		paddingTop: 23,
	},
	accBtn: {
		width: 170,
		height: 54,
		borderRadius: theme.shape.borderRadius,
		filter: "drop-shadow(0px 2px 6px rgba(74,106,149,0.2))",
		backgroundColor: "#ffffff",
		color: "#3a8dff",
		boxShadow: "none",
		marginRight: 35,
	},
	accAside: {
		fontSize: 14,
		color: "#b0b0b0",
		fontWeight: 400,
		textAlign: "center",
		marginRight: 35,
		whiteSpace: "nowrap",
		display: "flex",
		alignItems: "center",
		padding: "1rem 0",
	},
	image: {
		backgroundImage: `url(${bgImg})`,
		backgroundRepeat: "no-repeat",
		backgroundSize: "cover",
		backgroundPosition: "center",
	},
	box: {
		padding: 24,
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		minHeight: "100vh",
		flexDirection: "column",
		maxWidth: 900,
		margin: "auto",
	},
	form: {
		width: "100%", // Fix IE 11 issue.
		marginTop: theme.spacing(1),
	},
	label: {
		fontSize: 19,
		color: "rgb(0,0,0,0.4)",
		paddingLeft: "5px",
	},
	submit: {
		margin: theme.spacing(3, 2, 2),
		padding: 10,
		width: 160,
		height: 56,
		borderRadius: theme.shape.borderRadius,
		marginTop: 49,
		fontSize: 16,
		backgroundColor: "#3a8dff",
		fontWeight: "bold",
	},
	inputs: {
		marginTop: ".8rem",
		height: "2rem",
		padding: "5px",
	},
	link: { textDecoration: "none" },
	authHeader: {
		alignSelf: "flex-end",
		justifyContent: "flex-end",
		alignItems: "center",
		display: "flex",
		flexWrap: "wrap",
	},
	forgot: {
		paddingRight: 10,
		color: "#3a8dff",
	},
	dashboard: { backgroundColor: "#FFFFFF" },
	chatSideBanner: {
		display: "flex",
		flexDirection: "column",
		minHeight: "100vh",
		padding: "2rem 2rem",
	},
	userPanel: {
		display: "flex",
		alignItems: "center",
		marginBottom: "2rem",
	},
	userText: {
		fontWeight: 700,
		paddingLeft: "1rem",
		fontSize: 16,
	},
	chatTitle: {
		fontWeight: 700,
		fontSize: 20,
		margin: "1rem 0",
	},
	search: {
		position: "relative",
		borderRadius: theme.shape.borderRadius,
		backgroundColor: "#E9EEF9",
		marginLeft: 0,
		width: "300px",
		height: "50px",
		lineHeight: "18px",
	},
	searchIcon: {
		height: "100%",
		position: "absolute",
		pointerEvents: "none",
		marginLeft: "1rem",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	searchRoot: {
		color: "inherit",
		width: "100%",
		height: "100%",
	},
	searchInput: {
		padding: theme.spacing(1, 1, 1, 0),
		// vertical padding + font size from searchIcon
		paddingLeft: `calc(1em + ${theme.spacing(4)}px)`,
		width: "100%",
		fontWeight: 600,
	},
	chatSummaryContainer: { overflowY: "auto" },
	chatContainer: {
		display: "flex",
		alignItems: "center",
		margin: "1rem 0",
		width: "300px",
		height: "80px",
		padding: "0.5rem",
		background: "#ffffff",
		boxShadow: "0px 2px 10px rgba(88,133,196,0.05)",
		borderRadius: theme.shape.borderRadius,
		"&:hover": { cursor: "pointer" },
	},
	chatUser: { fontSize: "14px", fontWeight: 600 },
	lastMessage: {
		fontSize: "12px",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		overflow: "hidden",
		fontWeight: 600,
	},
	readLastMessage: {
		fontWeight: 400,
	},
	chatTextContainer: { padding: "0 1rem", width: "calc(100% - 2rem)" },
	activeChat: {
		display: "flex",
		flexDirection: "column",
		minHeight: "100vh",
		padding: "0 2rem",
	},
	activeChatHeader: {
		display: "flex",
		alignItems: "center",
		background: "#FFFFFF",
		padding: "2rem",
		borderRadius: theme.shape.borderRadius,
		boxShadow: "0px 2px 20px rgba(88,133,196,0.1)",
	},
	activeChatUser: {
		fontSize: 20,
		fontWeight: 700,
	},
	activeChatOnline: {
		marginLeft: "2rem",
		color: "#bfc9db",
		fontSize: 12,
	},
	inlineBadge: { bottom: "auto" },
	activeChatMessages: {
		marginTop: "2rem",
		display: "flex",
		flexDirection: "column",
		height: "70vh",
		overflowY: "auto",
		overflowX: "hidden",
	},
	message: {
		display: "flex",
		width: "100%",
		margin: "0.5rem 0",
	},
	messagesTextContainer: {
		display: "flex",
		flexDirection: "column",
		margin: "0 1rem",
		width: "100%",
	},
	messageContainerRight: { alignItems: "flex-end" },
	messageMetaData: { color: "#BECCE2", fontSize: 11, padding: "0.5rem" },
	messageText: {
		padding: "0.7rem",
		fontSize: "14px",
		boxShadow: "0px 2px 20px rgba(88,133,196,0.1)",
		width: "fit-content",
		maxWidth: "50%",
	},
	messageLeft: {
		background: "linear-gradient(225deg, #6CC1FF, #3A8DFF)",
		borderRadius: "0 8px 8px 8px",
		color: "#FFFFFF",
	},
	messageRight: {
		backgroundColor: "#F4F6FA",
		borderRadius: "8px 0px 8px 8px",
		color: "#91A3C0",
	},
}));

export default useStyles;
